### ISSUE TITLE
Issue with Session Query all

### ISSUE THREAD

**Issue by vsathiamoo** [cisco-pxgrid/pxgrid-rest-ws#2]
I have tried session_subscribe.py file and I am able to successfully subscribe and obtain information about sessions. However, when I run the session_query_all.py, I am getting 403 error. Unable to find out why session_subscribe works and session_query_all throws 403 error. 

pxgrid url=https://10.8.52.231:8910/pxgrid/control/AccessSecret
  request={"peerNodeName": "ise-mnt-ciscoise"}
  response={"secret":"w6cMtuPoe7G2TaiD"}
query url=https://ciscoise.test.local:8910/pxgrid/mnt/sd/getSessions
  request={}
B64:  cGFkbWluOnc2Y010dVBvZTdHMlRhaUQ=
Rest Req <urllib.request.Request object at 0x7eff45b6cba8>
Traceback (most recent call last):
  File "mod_session_query_all.py", line 40, in <module>
    query(config, secret, url, '{}')
  File "mod_session_query_all.py", line 21, in query
    rest_response = opener.open(rest_request)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by DR11110000** [comment]
Hi, 
Please check the username and password and also check the certificate you passing is correct. Because it directly means the server is refuse to connect.

**Comment by orpinchasov** [comment]
Hi, I'm getting the same issue. 403 no matter what I try. Is there any relevant configuration in ISE itself? Maybe the permissions page in the pxGrid dashboard? Thanks
